name: "INitialize Tf"

on: 
  workflow_dispatch: 
  # pull_request:
  #   branches: [main]

permissions: 
  id-token: write
  contents: read
env:
    "TABLE_NAME": ${{ secrets.TABLE_NAME }}
    "PARTITION_KEY": ${{ secrets.PARTITION_KEY }}
    "ITEM_NAME": ${{ secrets.ITEM_NAME }}
    "ATTRIBUTE": ${{ secrets.ATTRIBUTE }}

jobs:
  deploying:
      runs-on: ubuntu-latest
      steps:
          - name: "Checkout repo"
            uses: actions/checkout@v3
          
          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v1
            with:
              terraform_version: '1.4.0'

          - name: "Configure AWS Creds"
            uses: aws-actions/configure-aws-credentials@v4.1.0
            with:
              aws-region: ${{ secrets.AWS_REGION }}
              role-to-assume: ${{ secrets.OIDC }}
              role-session-name: role2
          
          - name: "Zip lambda function"
            working-directory: pytestt/app
            run: zip lambda_function_payload.zip lambda_function.py

          - name: "Terraform init"
            working-directory: Backend
            run: terraform init
          
          - name: "Apply plan"
            working-directory: Backend
            run: terraform plan

          - name: "Apply apply"
            working-directory: Backend
            run: terraform apply --auto-approve