name: Print GitHub JWT sub

on:
    workflow_dispatch: 
jobs:
  show-jwt-sub:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Request GitHub OIDC Token and print `sub`
        run: |
          echo "Requesting JWT..."
          token_response=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          jwt=$(echo "$token_response" | jq -r '.value')

          echo "JWT: $jwt"

          # Decode JWT and extract 'sub'
          sub=$(echo "$jwt" | cut -d '.' -f2 | base64 -d | jq -r '.sub')
          echo "sub claim: $sub"