name: "Test-Lambda"

on: 
  push:
    branches: [testing]

env:
    "API_URL": ${{ secrets.API_URL }}
jobs:
    prepare-creds:
        runs-on: ubuntu-latest
        environment: testing
        steps:
            - name: "Checkout repo"
              uses: actions/checkout@v3
            
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: '1.4.0'

            - name: "Configure AWS Creds"
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                aws-region: ${{ secrets.AWS_REGION }}
                role-to-assume: ${{ secrets.IAM_ARN }}
                role-session-name: samplerolesession
            
            - name: "Zip lambda function"
              run: zip lambda_function_payload.zip lambda_function.py

            - name: "Terraform init"
              working-directory: Backend
              run: terraform init
            
            - name: "Apply plan"
              working-directory: Backend
              run: terraform plan
            

    # lamda-test-job:
    #   runs-on: ubuntu-latest
    #   environment: testing
    #     - name: "Setup Python"
    #       uses: actions/setup-python@v5
    #       with:
    #         python-version: '3.9'
        
    #     - name: "Install requirements"
    #       working-directory: 
    #       run: pip install -r pytest/requirements.txt

    #     - name: "Run COR Test"
    #       run: pytest test_cors.py