name: "Test-Lambda"

on: 
    push: 
      branches: [testing]
env:
    "API_URL": ${{ secrets.API_URL }}
    "TABLE_NAME": ${{ secrets.TABLE_NAME }}
    "ITEM_NAME": ${{ secrets.ITEM_NAME }}
    "PARTITION_KEY": ${{secrets.PARTITION_KEY}}
    "ATTRIBUTE": ${{secrets.ATTRIBUTE}}

jobs:
    lamda-test-job:
        runs-on: ubuntu-latest
        # environment: testing
        steps:
            - name: "Checkout repo"
              uses: actions/checkout@v3
            
            - name: "Setup Python"
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
            
            - name: "Install requirements"
              working-directory: 
              run: pip install -r pytest/requirements.txt

            - name: "Run COR Test"
              run: pytest pytest/test_cors.py

            - name: "Run DB Test"
              run: pytest pytest/test_database_value.py

            - name: "Run Input Test"
              run: pytest pytest/test_input.py